name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Hello World
      run: g++ -static ./src/hello.cpp -o ./src/hello
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-cpp:1234
    - name: Run hello in Docker
      run: docker run hello-cpp:1234
